#!/bin/sh /etc/rc.common
# Periodic refresh of the NordVPN server-list cache.
# Runs the one-shot updater, then sleeps for the configured interval
# (re-read from UCI on every iteration).

START=99
USE_PROCD=1

start_service() {
	procd_open_instance nordvpn-cache
	procd_set_param command /bin/sh -c '
		while true; do
			/usr/bin/nordvpn-cache-update 2>&1 | logger -t nordvpn-cache
			interval=$(uci -q get nordvpn.settings.cache_refresh_interval)
			sleep "${interval:-21600}"
		done
	'
	procd_set_param respawn
	procd_close_instance
}
